#!/usr/bin/env python3
"""Generate browseable HTML API docs from package docstrings.

Uses ``pdoc`` (https://pdoc.dev) when installed; falls back to
a stdlib-only generator that walks each package + emits a
single-page index pointing at every public class/function with
its first-paragraph docstring.

Why two backends:

- ``pdoc`` produces vastly nicer output with cross-linked
  signatures + source-view, but adds a dev-time install. CI
  picks it up automatically when present.
- The stdlib fallback lets operators run this on a fresh checkout
  with zero extra installs and still get a useful overview.

Usage::

    python3 scripts/build_api_docs.py [--out docs/api]
                                       [--pdoc | --stdlib]

By default the script tries pdoc first + falls back. Pass
``--stdlib`` to skip pdoc even when installed (useful for
operators who want byte-stable output across hosts).
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List


PACKAGES = [
    "arq_writer",
    "arq_reader",
    "arq_validator",
    "arq_tui",
]


def _try_pdoc(out_dir: Path) -> bool:
    """Run ``pdoc -o <out> <packages...>``. Returns True on
    success, False if pdoc isn't installed or fails."""
    try:
        import pdoc  # noqa: F401
    except ImportError:
        return False
    cmd = [
        sys.executable, "-m", "pdoc",
        "-o", str(out_dir),
    ] + PACKAGES
    cp = subprocess.run(cmd)
    return cp.returncode == 0


def _stdlib_index(out_dir: Path, repo_root: Path) -> bool:
    """Fallback: walk each package's modules, collect every
    public class/function name + docstring's first paragraph,
    write a single-page Markdown index.

    Not as nice as pdoc but useful for spot-checking what's
    exported and what's documented."""
    sys.path.insert(0, str(repo_root))
    out_dir.mkdir(parents=True, exist_ok=True)
    index_md = out_dir / "index.md"
    lines: List[str] = [
        "# API reference\n",
        "Auto-generated by `scripts/build_api_docs.py`. "
        "Install [pdoc](https://pdoc.dev) for a richer browseable "
        "version under the same path.\n",
    ]
    for pkg_name in PACKAGES:
        try:
            pkg = importlib.import_module(pkg_name)
        except ImportError as exc:
            lines.append(
                f"## `{pkg_name}` — IMPORT FAILED: {exc}\n"
            )
            continue
        lines.append(f"## `{pkg_name}`\n")
        # Walk every submodule.
        for sub in _iter_submodules(pkg, repo_root):
            mod_lines = _module_lines(sub)
            if mod_lines:
                lines.extend(mod_lines)
    index_md.write_text("\n".join(lines), encoding="utf-8")
    return True


def _iter_submodules(pkg, repo_root: Path):
    """Yield each submodule of ``pkg`` (top-level only — we don't
    recurse into sub-packages here). Skips dunder + private."""
    pkg_path = Path(pkg.__file__).parent
    for fp in sorted(pkg_path.glob("*.py")):
        name = fp.stem
        if name.startswith("_"):
            continue
        try:
            yield importlib.import_module(f"{pkg.__name__}.{name}")
        except Exception:
            continue


def _module_lines(mod) -> List[str]:
    """Return Markdown lines describing ``mod``'s public members."""
    out: List[str] = []
    members = []
    for name, obj in vars(mod).items():
        if name.startswith("_"):
            continue
        if not (inspect.isclass(obj) or inspect.isfunction(obj)):
            continue
        # Only include things actually defined in this module.
        if getattr(obj, "__module__", "") != mod.__name__:
            continue
        members.append((name, obj))
    if not members:
        return out
    out.append(f"### `{mod.__name__}`\n")
    if mod.__doc__:
        first_para = mod.__doc__.strip().split("\n\n")[0]
        out.append(f"{first_para}\n")
    for name, obj in sorted(members):
        kind = "class" if inspect.isclass(obj) else "def"
        try:
            sig = str(inspect.signature(obj))
        except (TypeError, ValueError):
            sig = "(...)"
        doc = inspect.getdoc(obj) or ""
        first_para = doc.split("\n\n")[0] if doc else ""
        out.append(f"- **`{kind} {name}{sig}`**")
        if first_para:
            out.append(f"  {first_para}")
        out.append("")
    return out


def _main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", type=Path, default=None,
                   help="output directory (default docs/api/)")
    p.add_argument("--pdoc", action="store_true",
                   help="require pdoc; fail if not installed")
    p.add_argument("--stdlib", action="store_true",
                   help="force the stdlib fallback even when "
                        "pdoc is available")
    args = p.parse_args(argv)
    repo_root = Path(__file__).resolve().parent.parent
    out_dir = args.out or (repo_root / "docs" / "api")

    if args.stdlib:
        ok = _stdlib_index(out_dir, repo_root)
    elif args.pdoc:
        ok = _try_pdoc(out_dir)
        if not ok:
            print("pdoc not installed; install with `pip install pdoc`",
                  file=sys.stderr)
            return 1
    else:
        ok = _try_pdoc(out_dir)
        if not ok:
            print("pdoc unavailable, falling back to stdlib generator",
                  file=sys.stderr)
            ok = _stdlib_index(out_dir, repo_root)
    if ok:
        print(f"wrote API docs to {out_dir}", file=sys.stderr)
        return 0
    return 1


if __name__ == "__main__":
    sys.exit(_main())
