-- N2: Arq.app local-cache SQLite schema (extracted)
-- Source: /Applications/Arq.app/Contents/Resources/ArqAgent.app/Contents/MacOS/ArqAgent
-- Each statement is a raw string visible in the Mach-O
-- binary. Extracted via ``strings`` + regex; do not
-- run this as a live schema (column orderings may
-- differ from Arq.app's runtime CREATE because of
-- whitespace normalisation).

-- 122 CREATE statements found

CREATE TABLE IF NOT EXISTS initialized (id INTEGER PRIMARY KEY AUTOINCREMENT, value INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS relative_dirs ( id INTEGER PRIMARY KEY AUTOINCREMENT, path TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS unpacked_blobs ( id INTEGER PRIMARY KEY AUTOINCREMENT, relative_dir_id INTEGER NOT NULL, filename TEXT NOT NULL, storage_class TEXT NOT NULL, blob_identifier TEXT NOT NULL, length INTEGER NOT NULL, stretch_encryption_key INTEGER, compression_type INTEGER, item_checksum TEXT, FOREIGN KEY (relative_dir_id) REFERENCES relative_dirs(id));
CREATE INDEX IF NOT EXISTS unpacked_blobs_identifier_storage_class ON unpacked_blobs (blob_identifier, storage_class);
CREATE TABLE IF NOT EXISTS pack_files ( id INTEGER PRIMARY KEY AUTOINCREMENT, relative_dir_id INTEGER NOT NULL, filename TEXT NOT NULL, storage_class TEXT NOT NULL, committed INTEGER NOT NULL, length INTEGER, item_checksum TEXT, FOREIGN KEY (relative_dir_id) REFERENCES relative_dirs(id));
CREATE TABLE IF NOT EXISTS packed_blobs ( id INTEGER PRIMARY KEY AUTOINCREMENT, blob_identifier TEXT NOT NULL, pack_file_id INTEGER NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL, stretch_encryption_key INTEGER NOT NULL, compression_type INTEGER NOT NULL, backup_folder_uuid TEXT NOT NULL, FOREIGN KEY (pack_file_id) REFERENCES pack_files(id));
CREATE INDEX IF NOT EXISTS packed_blobs_pack_file_id ON packed_blobs (pack_file_id);
CREATE INDEX IF NOT EXISTS packed_blobs_blob_identifier ON packed_blobs (blob_identifier);
CREATE TABLE IF NOT EXISTS trees ( id INTEGER PRIMARY KEY AUTOINCREMENT, pack_file_id INTEGER NOT NULL, blob_identifier TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL, backup_folder_uuid TEXT NOT NULL, FOREIGN KEY (pack_file_id) REFERENCES pack_files(id));
CREATE INDEX IF NOT EXISTS trees_pack_file_id ON trees (pack_file_id);
CREATE INDEX IF NOT EXISTS trees_blob_identifier ON trees (blob_identifier);
CREATE TABLE IF NOT EXISTS backup_records ( id INTEGER PRIMARY KEY AUTOINCREMENT, backup_folder_uuid TEXT NOT NULL, relative_path TEXT NOT NULL, date_created DATETIME NOT NULL, is_complete INTEGER NOT NULL, item_checksum TEXT);
CREATE INDEX IF NOT EXISTS backup_records_relative_path ON backup_records(relative_path);
CREATE TABLE IF NOT EXISTS names(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);
CREATE INDEX IF NOT EXISTS names_name ON names (name);
CREATE TABLE IF NOT EXISTS tree_tree_refs ( referring_tree_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), referred_to_tree_id INTEGER REFERENCES trees(id), PRIMARY KEY (referring_tree_id, name_id, referred_to_tree_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS ttr_referring_tree_id ON tree_tree_refs (referring_tree_id);
CREATE INDEX IF NOT EXISTS ttr_referred_to_tree_id ON tree_tree_refs (referred_to_tree_id);
CREATE TABLE IF NOT EXISTS tree_unpacked_blob_refs ( referring_tree_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_unpacked_blob_id INTEGER REFERENCES unpacked_blobs(id), PRIMARY KEY (referring_tree_id, name_id, blob_index, referred_to_unpacked_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS tubr_referred_to_blob_id ON tree_unpacked_blob_refs (referred_to_unpacked_blob_id);
CREATE TABLE IF NOT EXISTS tree_packed_blob_refs (referring_tree_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_packed_blob_id INTEGER REFERENCES packed_blobs(id), PRIMARY KEY (referring_tree_id, name_id, blob_index, referred_to_packed_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS tpbr_referred_to_blob_id ON tree_packed_blob_refs (referred_to_packed_blob_id);
CREATE TABLE IF NOT EXISTS backup_record_tree_refs ( backup_record_id INTEGER REFERENCES backup_records(id), referred_to_tree_id INTEGER REFERENCES trees(id), PRIMARY KEY (backup_record_id, referred_to_tree_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS brtr_backup_record_id ON backup_record_tree_refs(backup_record_id);
CREATE INDEX IF NOT EXISTS brtr_tree_id ON backup_record_tree_refs(referred_to_tree_id);
CREATE TABLE IF NOT EXISTS backup_record_unpacked_blob_refs ( backup_record_id INTEGER REFERENCES backup_records(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_unpacked_blob_id INTEGER REFERENCES unpacked_blobs(id), PRIMARY KEY (backup_record_id, name_id, blob_index, referred_to_unpacked_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS brubr_referred_to_blob_id ON backup_record_unpacked_blob_refs (referred_to_unpacked_blob_id);
CREATE TABLE IF NOT EXISTS backup_record_packed_blob_refs ( backup_record_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_packed_blob_id INTEGER REFERENCES packed_blobs(id), PRIMARY KEY (backup_record_id, name_id, blob_index, referred_to_packed_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS brpbr_referred_to_blob_id ON backup_record_packed_blob_refs (referred_to_packed_blob_id);
CREATE TABLE IF NOT EXISTS index_schema (version INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS directories ( id INTEGER PRIMARY KEY AUTOINCREMENT, path TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, directory_id INTEGER NOT NULL, item_id TEXT, name TEXT NOT NULL, is_directory INTEGER NOT NULL, file_size INTEGER, file_last_modified DATETIME, created_date DATETIME, storage_class TEXT, checksum TEXT, FOREIGN KEY (directory_id) REFERENCES directories(id));
CREATE TABLE IF NOT EXISTS packs (pack_sha1 TEXT NOT NULL PRIMARY KEY, pack_set_name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pack_index_entries (object_sha1 TEXT NOT NULL PRIMARY KEY, pack_sha1 TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL);
CREATE INDEX pack_index_entries_pack_sha1 ON pack_index_entries (pack_sha1);
CREATE TABLE IF NOT EXISTS packset_schema (version INTEGER NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS loaded_directories (path TEXT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS items (item_id TEXT NOT NULL PRIMARY KEY, path TEXT NOT NULL, parent_item_id TEXT NOT NULL, is_directory INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS items_parent_item_id ON items(parent_item_id);
CREATE TABLE IF NOT EXISTS items (path TEXT NOT NULL PRIMARY KEY, item_id TEXT NOT NULL, parent_item_id TEXT NOT NULL, is_directory INTEGER NOT NULL);
CREATE TABLE index_schema (version INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS items (path TEXT NOT NULL PRIMARY KEY, item_id TEXT NOT NULL);
CREATE TABLE users ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, uuid TEXT NOT NULL, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL );
CREATE TABLE users_history ( id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, uuid TEXT NOT NULL, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL );
CREATE TABLE storage_locations ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, name TEXT NOT NULL, plan_type TEXT NOT NULL, provider_type TEXT NOT NULL, username TEXT, password TEXT, private_key_path TEXT, private_key_passphrase TEXT, hostname TEXT, port INTEGER, use_ssl INTEGER, path TEXT, region_name TEXT );
CREATE TABLE storage_locations_history ( id INTEGER PRIMARY KEY AUTOINCREMENT, storage_location_id INTEGER NOT NULL, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, name TEXT NOT NULL, plan_type TEXT NOT NULL, provider_type TEXT NOT NULL, username TEXT, password TEXT, hostname TEXT, port INTEGER, use_ssl INTEGER, path TEXT, region_name TEXT );
CREATE TABLE backup_plans ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, storage_location_id INTEGER NOT NULL, blob_storage_class TEXT, files_option INTEGER NOT NULL, selected_keys TEXT, smb_path TEXT, smb_username TEXT, smb_password TEXT, exclude_rules TEXT NOT NULL, encryption_password TEXT, schedule_json TEXT NOT NULL, retain_all INTEGER NOT NULL, retain_hours INTEGER NOT NULL, retain_days INTEGER NOT NULL, retain_weeks INTEGER NOT NULL, retain_months INTEGER NOT NULL, use_apfs_snapshots INTEGER NOT NULL, keep_deleted_files INTEGER NOT NULL, wake_for_backup INTEGER NOT NULL, prevent_sleep INTEGER NOT NULL, notify_on_error INTEGER NOT NULL, notify_on_success INTEGER NOT NULL, transfer_rate_json TEXT NOT NULL, no_backups_alert_days INTEGER, name TEXT NOT NULL, plan_uuid TEXT NOT NULL, thread_count INTEGER NOT NULL, pause_on_battery INTEGER NOT NULL, include_new_volumes INTEGER NOT NULL, use_buzhash INTEGER NOT NULL, skip_tm_excludes INTEGER NOT NULL, excluded_network_interfaces TEXT NOT NULL, excluded_wifi_network_names TEXT NOT NULL, email_report_json TEXT NOT NULL, budget_gb REAL, preflight_script TEXT, postflight_script TEXT, FOREIGN KEY (storage_location_id) REFERENCES storage_locations(id) );
CREATE TABLE backup_plans_history ( id INTEGER PRIMARY KEY AUTOINCREMENT, backup_plan_id INTEGER NOT NULL, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, storage_location_id INTEGER NOT NULL, blob_storage_class TEXT, files_option TEXT NOT NULL, selected_keys TEXT, smb_path TEXT NOT NULL, smb_username TEXT NOT NULL, smb_password TEXT NOT NULL, exclude_rules TEXT NOT NULL, encryption_password TEXT, schedule_json TEXT NOT NULL, retain_all INTEGER NOT NULL, retain_hours INTEGER NOT NULL, retain_days INTEGER NOT NULL, retain_weeks INTEGER NOT NULL, retain_months INTEGER NOT NULL, use_apfs_snapshots INTEGER NOT NULL, keep_deleted_files INTEGER NOT NULL, wake_for_backup INTEGER NOT NULL, prevent_sleep INTEGER NOT NULL, notify_on_error INTEGER NOT NULL, notify_on_success INTEGER NOT NULL, transfer_rate_json TEXT NOT NULL, no_backups_alert_days INTEGER, name TEXT NOT NULL, plan_uuid TEXT NOT NULL, thread_count INTEGER NOT NULL, pause_on_battery INTEGER NOT NULL, include_new_volumes INTEGER NOT NULL, use_buzhash INTEGER NOT NULL, skip_tm_excludes INTEGER NOT NULL, excluded_network_interfaces TEXT NOT NULL, excluded_wifi_network_names TEXT NOT NULL, email_report_json TEXT NOT NULL, budget_gb REAL, preflight_script TEXT, postflight_script TEXT, FOREIGN KEY (storage_location_id) REFERENCES storage_locations(id) );
CREATE TABLE restore_jobs ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, storage_location_id INTEGER NOT NULL, snapshot_json TEXT NOT NULL, selected_keys TEXT NOT NULL, restore_to_original_location INTEGER NOT NULL, restore_location TEXT, errors TEXT NOT NULL, activity_id INTEGER NOT NULL, FOREIGN KEY (storage_location_id) REFERENCES storage_locations(id) FOREIGN KEY (activity_id) REFERENCES activities(id) );
CREATE TABLE activities ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, uuid TEXT NOT NULL, type TEXT NOT NULL, sub_type TEXT NOT NULL, message TEXT NOT NULL, processed_bytes INTEGER NOT NULL, total_bytes INTEGER, processed_files INTEGER NOT NULL, total_files INTEGER, uploaded_files_count INTEGER, current_file TEXT, finished_time REAL, snapshot_path TEXT, aborted INTEGER NOT NULL, abort_reason TEXT, plan_uuid TEXT, activity_log_path TEXT, error_count INTEGER, snapshot_json TEXT, selected_keys TEXT, restore_option TEXT );
CREATE TABLE legacy_backups ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, computer_uuid TEXT NOT NULL, storage_location_id INTEGER NOT NULL, schedule_type TEXT NOT NULL, schedule_number_of_hours INTEGER NOT NULL, schedule_minutes_after_hour INTEGER NOT NULL, schedule_backup_hour INTEGER NOT NULL, thin_backups INTEGER NOT NULL, budget_enforcement_interval_hours INTEGER NOT NULL, data_validation_interval_hours INTEGER NOT NULL, pause_during_window INTEGER NOT NULL, pause_from_hour INTEGER NOT NULL, pause_to_hour INTEGER NOT NULL, storage_class TEXT, encryption_password TEXT, prevent_sleep INTEGER NOT NULL, notify_on_successful_backup INTEGER NOT NULL, max_kbps INTEGER, pause_on_battery INTEGER NOT NULL, budget_gb REAL, preflight_script TEXT, postflight_script TEXT, email_report_json TEXT, import_activity_uuid TEXT, found_at_install INTEGER NOT NULL );
CREATE TABLE imported_legacy_commits ( id INTEGER PRIMARY KEY AUTOINCREMENT, sha1 TEXT NOT NULL, bucket_uuid TEXT NOT NULL );
CREATE INDEX activities_updated_time ON activities (plan_uuid, updated_time);
CREATE TABLE activity_errors ( id INTEGER PRIMARY KEY AUTOINCREMENT, activity_uuid TEXT NOT NULL REFERENCES activities(uuid) ON DELETE CASCADE, severity INTEGER NOT NULL DEFAULT 0, error_domain TEXT, error_code INTEGER NOT NULL DEFAULT 0, error_message TEXT, local_path TEXT, relative_path TEXT, volume_name TEXT, disk_identifier TEXT, backup_folder_uuid TEXT, path_is_directory INTEGER NOT NULL DEFAULT 0, aggregated_count INTEGER NOT NULL DEFAULT 1, created_time REAL NOT NULL, sync_needed INTEGER NOT NULL DEFAULT 1);
CREATE INDEX activity_errors_activity_uuid ON activity_errors(activity_uuid);
CREATE INDEX activity_errors_sync_needed ON activity_errors(sync_needed);
CREATE TABLE IF NOT EXISTS glacier_pack_index_entries (object_sha1 TEXT NOT NULL PRIMARY KEY, archive_id TEXT NOT NULL, pack_sha1 TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL);
CREATE INDEX glacier_pack_index_entries_pack_sha1 ON glacier_pack_index_entries (pack_sha1);
CREATE INDEX glacier_pack_index_entries_object_sha1 ON glacier_pack_index_entries (object_sha1);
CREATE TABLE IF NOT EXISTS nodes ( id INTEGER PRIMARY KEY AUTOINCREMENT, sha1 TEXT NOT NULL UNIQUE, node_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS nodes_sha1 ON nodes (sha1);
CREATE TABLE IF NOT EXISTS initialized (id INTEGER PRIMARY KEY AUTOINCREMENT, value INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS relative_dirs ( id INTEGER PRIMARY KEY AUTOINCREMENT, path TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS unpacked_blobs ( id INTEGER PRIMARY KEY AUTOINCREMENT, relative_dir_id INTEGER NOT NULL, filename TEXT NOT NULL, storage_class TEXT NOT NULL, blob_identifier TEXT NOT NULL, length INTEGER NOT NULL, stretch_encryption_key INTEGER, compression_type INTEGER, item_checksum TEXT, FOREIGN KEY (relative_dir_id) REFERENCES relative_dirs(id));
CREATE INDEX IF NOT EXISTS unpacked_blobs_identifier_storage_class ON unpacked_blobs (blob_identifier, storage_class);
CREATE TABLE IF NOT EXISTS pack_files ( id INTEGER PRIMARY KEY AUTOINCREMENT, relative_dir_id INTEGER NOT NULL, filename TEXT NOT NULL, storage_class TEXT NOT NULL, committed INTEGER NOT NULL, length INTEGER, item_checksum TEXT, FOREIGN KEY (relative_dir_id) REFERENCES relative_dirs(id));
CREATE TABLE IF NOT EXISTS packed_blobs ( id INTEGER PRIMARY KEY AUTOINCREMENT, blob_identifier TEXT NOT NULL, pack_file_id INTEGER NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL, stretch_encryption_key INTEGER NOT NULL, compression_type INTEGER NOT NULL, backup_folder_uuid TEXT NOT NULL, FOREIGN KEY (pack_file_id) REFERENCES pack_files(id));
CREATE INDEX IF NOT EXISTS packed_blobs_pack_file_id ON packed_blobs (pack_file_id);
CREATE INDEX IF NOT EXISTS packed_blobs_blob_identifier ON packed_blobs (blob_identifier);
CREATE TABLE IF NOT EXISTS trees ( id INTEGER PRIMARY KEY AUTOINCREMENT, pack_file_id INTEGER NOT NULL, blob_identifier TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL, backup_folder_uuid TEXT NOT NULL, FOREIGN KEY (pack_file_id) REFERENCES pack_files(id));
CREATE INDEX IF NOT EXISTS trees_pack_file_id ON trees (pack_file_id);
CREATE INDEX IF NOT EXISTS trees_blob_identifier ON trees (blob_identifier);
CREATE TABLE IF NOT EXISTS backup_records ( id INTEGER PRIMARY KEY AUTOINCREMENT, backup_folder_uuid TEXT NOT NULL, relative_path TEXT NOT NULL, date_created DATETIME NOT NULL, is_complete INTEGER NOT NULL, item_checksum TEXT);
CREATE INDEX IF NOT EXISTS backup_records_relative_path ON backup_records(relative_path);
CREATE TABLE IF NOT EXISTS names(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);
CREATE INDEX IF NOT EXISTS names_name ON names (name);
CREATE TABLE IF NOT EXISTS tree_tree_refs ( referring_tree_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), referred_to_tree_id INTEGER REFERENCES trees(id), PRIMARY KEY (referring_tree_id, name_id, referred_to_tree_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS ttr_referring_tree_id ON tree_tree_refs (referring_tree_id);
CREATE INDEX IF NOT EXISTS ttr_referred_to_tree_id ON tree_tree_refs (referred_to_tree_id);
CREATE TABLE IF NOT EXISTS tree_unpacked_blob_refs ( referring_tree_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_unpacked_blob_id INTEGER REFERENCES unpacked_blobs(id), PRIMARY KEY (referring_tree_id, name_id, blob_index, referred_to_unpacked_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS tubr_referred_to_blob_id ON tree_unpacked_blob_refs (referred_to_unpacked_blob_id);
CREATE TABLE IF NOT EXISTS tree_packed_blob_refs (referring_tree_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_packed_blob_id INTEGER REFERENCES packed_blobs(id), PRIMARY KEY (referring_tree_id, name_id, blob_index, referred_to_packed_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS tpbr_referred_to_blob_id ON tree_packed_blob_refs (referred_to_packed_blob_id);
CREATE TABLE IF NOT EXISTS backup_record_tree_refs ( backup_record_id INTEGER REFERENCES backup_records(id), referred_to_tree_id INTEGER REFERENCES trees(id), PRIMARY KEY (backup_record_id, referred_to_tree_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS brtr_backup_record_id ON backup_record_tree_refs(backup_record_id);
CREATE INDEX IF NOT EXISTS brtr_tree_id ON backup_record_tree_refs(referred_to_tree_id);
CREATE TABLE IF NOT EXISTS backup_record_unpacked_blob_refs ( backup_record_id INTEGER REFERENCES backup_records(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_unpacked_blob_id INTEGER REFERENCES unpacked_blobs(id), PRIMARY KEY (backup_record_id, name_id, blob_index, referred_to_unpacked_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS brubr_referred_to_blob_id ON backup_record_unpacked_blob_refs (referred_to_unpacked_blob_id);
CREATE TABLE IF NOT EXISTS backup_record_packed_blob_refs ( backup_record_id INTEGER REFERENCES trees(id), name_id INTEGER REFERENCES names(id), blob_index INTEGER, referred_to_packed_blob_id INTEGER REFERENCES packed_blobs(id), PRIMARY KEY (backup_record_id, name_id, blob_index, referred_to_packed_blob_id)) WITHOUT ROWID;
CREATE INDEX IF NOT EXISTS brpbr_referred_to_blob_id ON backup_record_packed_blob_refs (referred_to_packed_blob_id);
CREATE TABLE IF NOT EXISTS index_schema (version INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS directories ( id INTEGER PRIMARY KEY AUTOINCREMENT, path TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, directory_id INTEGER NOT NULL, item_id TEXT, name TEXT NOT NULL, is_directory INTEGER NOT NULL, file_size INTEGER, file_last_modified DATETIME, created_date DATETIME, storage_class TEXT, checksum TEXT, FOREIGN KEY (directory_id) REFERENCES directories(id));
CREATE TABLE IF NOT EXISTS packs (pack_sha1 TEXT NOT NULL PRIMARY KEY, pack_set_name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pack_index_entries (object_sha1 TEXT NOT NULL PRIMARY KEY, pack_sha1 TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL);
CREATE INDEX pack_index_entries_pack_sha1 ON pack_index_entries (pack_sha1);
CREATE TABLE IF NOT EXISTS packset_schema (version INTEGER NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS loaded_directories (path TEXT NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS items (item_id TEXT NOT NULL PRIMARY KEY, path TEXT NOT NULL, parent_item_id TEXT NOT NULL, is_directory INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS items_parent_item_id ON items(parent_item_id);
CREATE TABLE IF NOT EXISTS items (path TEXT NOT NULL PRIMARY KEY, item_id TEXT NOT NULL, parent_item_id TEXT NOT NULL, is_directory INTEGER NOT NULL);
CREATE TABLE index_schema (version INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS items (path TEXT NOT NULL PRIMARY KEY, item_id TEXT NOT NULL);
CREATE TABLE users ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, uuid TEXT NOT NULL, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL );
CREATE TABLE users_history ( id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, uuid TEXT NOT NULL, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL );
CREATE TABLE storage_locations ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, name TEXT NOT NULL, plan_type TEXT NOT NULL, provider_type TEXT NOT NULL, username TEXT, password TEXT, private_key_path TEXT, private_key_passphrase TEXT, hostname TEXT, port INTEGER, use_ssl INTEGER, path TEXT, region_name TEXT );
CREATE TABLE storage_locations_history ( id INTEGER PRIMARY KEY AUTOINCREMENT, storage_location_id INTEGER NOT NULL, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, name TEXT NOT NULL, plan_type TEXT NOT NULL, provider_type TEXT NOT NULL, username TEXT, password TEXT, hostname TEXT, port INTEGER, use_ssl INTEGER, path TEXT, region_name TEXT );
CREATE TABLE backup_plans ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, storage_location_id INTEGER NOT NULL, blob_storage_class TEXT, files_option INTEGER NOT NULL, selected_keys TEXT, smb_path TEXT, smb_username TEXT, smb_password TEXT, exclude_rules TEXT NOT NULL, encryption_password TEXT, schedule_json TEXT NOT NULL, retain_all INTEGER NOT NULL, retain_hours INTEGER NOT NULL, retain_days INTEGER NOT NULL, retain_weeks INTEGER NOT NULL, retain_months INTEGER NOT NULL, use_apfs_snapshots INTEGER NOT NULL, keep_deleted_files INTEGER NOT NULL, wake_for_backup INTEGER NOT NULL, prevent_sleep INTEGER NOT NULL, notify_on_error INTEGER NOT NULL, notify_on_success INTEGER NOT NULL, transfer_rate_json TEXT NOT NULL, no_backups_alert_days INTEGER, name TEXT NOT NULL, plan_uuid TEXT NOT NULL, thread_count INTEGER NOT NULL, pause_on_battery INTEGER NOT NULL, include_new_volumes INTEGER NOT NULL, use_buzhash INTEGER NOT NULL, skip_tm_excludes INTEGER NOT NULL, excluded_network_interfaces TEXT NOT NULL, excluded_wifi_network_names TEXT NOT NULL, email_report_json TEXT NOT NULL, budget_gb REAL, preflight_script TEXT, postflight_script TEXT, FOREIGN KEY (storage_location_id) REFERENCES storage_locations(id) );
CREATE TABLE backup_plans_history ( id INTEGER PRIMARY KEY AUTOINCREMENT, backup_plan_id INTEGER NOT NULL, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, storage_location_id INTEGER NOT NULL, blob_storage_class TEXT, files_option TEXT NOT NULL, selected_keys TEXT, smb_path TEXT NOT NULL, smb_username TEXT NOT NULL, smb_password TEXT NOT NULL, exclude_rules TEXT NOT NULL, encryption_password TEXT, schedule_json TEXT NOT NULL, retain_all INTEGER NOT NULL, retain_hours INTEGER NOT NULL, retain_days INTEGER NOT NULL, retain_weeks INTEGER NOT NULL, retain_months INTEGER NOT NULL, use_apfs_snapshots INTEGER NOT NULL, keep_deleted_files INTEGER NOT NULL, wake_for_backup INTEGER NOT NULL, prevent_sleep INTEGER NOT NULL, notify_on_error INTEGER NOT NULL, notify_on_success INTEGER NOT NULL, transfer_rate_json TEXT NOT NULL, no_backups_alert_days INTEGER, name TEXT NOT NULL, plan_uuid TEXT NOT NULL, thread_count INTEGER NOT NULL, pause_on_battery INTEGER NOT NULL, include_new_volumes INTEGER NOT NULL, use_buzhash INTEGER NOT NULL, skip_tm_excludes INTEGER NOT NULL, excluded_network_interfaces TEXT NOT NULL, excluded_wifi_network_names TEXT NOT NULL, email_report_json TEXT NOT NULL, budget_gb REAL, preflight_script TEXT, postflight_script TEXT, FOREIGN KEY (storage_location_id) REFERENCES storage_locations(id) );
CREATE TABLE restore_jobs ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, storage_location_id INTEGER NOT NULL, snapshot_json TEXT NOT NULL, selected_keys TEXT NOT NULL, restore_to_original_location INTEGER NOT NULL, restore_location TEXT, errors TEXT NOT NULL, activity_id INTEGER NOT NULL, FOREIGN KEY (storage_location_id) REFERENCES storage_locations(id) FOREIGN KEY (activity_id) REFERENCES activities(id) );
CREATE TABLE activities ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, uuid TEXT NOT NULL, type TEXT NOT NULL, sub_type TEXT NOT NULL, message TEXT NOT NULL, processed_bytes INTEGER NOT NULL, total_bytes INTEGER, processed_files INTEGER NOT NULL, total_files INTEGER, uploaded_files_count INTEGER, current_file TEXT, finished_time REAL, snapshot_path TEXT, aborted INTEGER NOT NULL, abort_reason TEXT, plan_uuid TEXT, activity_log_path TEXT, error_count INTEGER, snapshot_json TEXT, selected_keys TEXT, restore_option TEXT );
CREATE TABLE legacy_backups ( id INTEGER PRIMARY KEY AUTOINCREMENT, active INTEGER NOT NULL, created_time REAL NOT NULL, updated_time REAL NOT NULL, computer_uuid TEXT NOT NULL, storage_location_id INTEGER NOT NULL, schedule_type TEXT NOT NULL, schedule_number_of_hours INTEGER NOT NULL, schedule_minutes_after_hour INTEGER NOT NULL, schedule_backup_hour INTEGER NOT NULL, thin_backups INTEGER NOT NULL, budget_enforcement_interval_hours INTEGER NOT NULL, data_validation_interval_hours INTEGER NOT NULL, pause_during_window INTEGER NOT NULL, pause_from_hour INTEGER NOT NULL, pause_to_hour INTEGER NOT NULL, storage_class TEXT, encryption_password TEXT, prevent_sleep INTEGER NOT NULL, notify_on_successful_backup INTEGER NOT NULL, max_kbps INTEGER, pause_on_battery INTEGER NOT NULL, budget_gb REAL, preflight_script TEXT, postflight_script TEXT, email_report_json TEXT, import_activity_uuid TEXT, found_at_install INTEGER NOT NULL );
CREATE TABLE imported_legacy_commits ( id INTEGER PRIMARY KEY AUTOINCREMENT, sha1 TEXT NOT NULL, bucket_uuid TEXT NOT NULL );
CREATE INDEX activities_updated_time ON activities (plan_uuid, updated_time);
CREATE TABLE activity_errors ( id INTEGER PRIMARY KEY AUTOINCREMENT, activity_uuid TEXT NOT NULL REFERENCES activities(uuid) ON DELETE CASCADE, severity INTEGER NOT NULL DEFAULT 0, error_domain TEXT, error_code INTEGER NOT NULL DEFAULT 0, error_message TEXT, local_path TEXT, relative_path TEXT, volume_name TEXT, disk_identifier TEXT, backup_folder_uuid TEXT, path_is_directory INTEGER NOT NULL DEFAULT 0, aggregated_count INTEGER NOT NULL DEFAULT 1, created_time REAL NOT NULL, sync_needed INTEGER NOT NULL DEFAULT 1);
CREATE INDEX activity_errors_activity_uuid ON activity_errors(activity_uuid);
CREATE INDEX activity_errors_sync_needed ON activity_errors(sync_needed);
CREATE TABLE IF NOT EXISTS glacier_pack_index_entries (object_sha1 TEXT NOT NULL PRIMARY KEY, archive_id TEXT NOT NULL, pack_sha1 TEXT NOT NULL, offset INTEGER NOT NULL, length INTEGER NOT NULL);
CREATE INDEX glacier_pack_index_entries_pack_sha1 ON glacier_pack_index_entries (pack_sha1);
CREATE INDEX glacier_pack_index_entries_object_sha1 ON glacier_pack_index_entries (object_sha1);
CREATE TABLE IF NOT EXISTS nodes ( id INTEGER PRIMARY KEY AUTOINCREMENT, sha1 TEXT NOT NULL UNIQUE, node_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS nodes_sha1 ON nodes (sha1);

-- 66 SELECT/UPDATE statements touching pack_files / packed_blobs

-- SELECT pfrd.path, pf.filename, t.offset, t.length, t.blob_identifier, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, trees t WHERE pf.id = t.pack_file_id AND pf.relative_dir_id = pfrd.id AND pf.committed = 0 AND (SELECT COUNT(*) FROM tree_tree_refs WHERE referred_to_tree_id = t.id) = 0
-- SELECT pfrd.path, pf.filename, pb.offset, pb.length, pb.stretch_encryption_key, pb.compression_type, pb.id, pf.committed, pf.locked_until, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, packed_blobs pb WHERE pb.valid = 1 AND pf.id = pb.pack_file_id AND pf.relative_dir_id = pfrd.id AND pb.blob_identifier = ? AND pf.storage_class = ? ORDER BY pb.id DESC LIMIT 1
-- SELECT pfrd.path, pf.filename, t.offset, t.length, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, trees t WHERE pf.id = t.pack_file_id AND pf.relative_dir_id = pfrd.id AND t.blob_identifier = ? AND t.valid = 1 ORDER BY pf.id DESC LIMIT 1
-- SELECT COUNT(*), SUM(length) FROM unpacked_blobs WHERE stretch_encryption_key IS NULL OR compression_type IS NULL
-- SELECT rd.path, ub.filename FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND ub.id IN (SELECT id FROM unpacked_blobs WHERE stretch_encryption_key IS NULL OR compression_type IS NULL) ORDER BY rd.path, ub.filename
-- SELECT rd.path, ub.filename, ub.length, ub.stretch_encryption_key, ub.compression_type, ub.item_checksum, ub.id, ub.locked_until FROM unpacked_blobs ub, relative_dirs rd WHERE ub.valid = 1 AND ub.relative_dir_id = rd.id AND ub.blob_identifier = ? AND ub.storage_class = ? ORDER BY ub.id
-- SELECT ub.id, ub.stretch_encryption_key, ub.compression_type FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND rd.path = ? AND ub.filename = ? AND ub.valid =1 ORDER BY ub.id DESC
-- SELECT id FROM pack_files WHERE relative_dir_id = ? AND filename = ?
-- SELECT rd.path, pf.filename FROM pack_files pf, relative_dirs rd WHERE pf.relative_dir_id = rd.id AND (SELECT COUNT(*) FROM packed_blobs WHERE pack_file_id = pf.id) = 0 AND (SELECT COUNT(*) FROM trees WHERE pack_file_id = pf.id) = 0
-- SELECT SUM(length) FROM pack_files
-- SELECT SUM(length) FROM unpacked_blobs
-- SELECT SUM(length) FROM pack_files WHERE storage_class = ?
-- SELECT SUM(length) FROM unpacked_blobs WHERE storage_class = ?
-- SELECT pfrd.path, pf.filename, t.offset, t.length, t.blob_identifier, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, trees t WHERE pf.id = t.pack_file_id AND pf.relative_dir_id = pfrd.id AND (SELECT COUNT(*) FROM backup_record_tree_refs WHERE referred_to_tree_id = t.id) = 0 AND (SELECT COUNT(*) FROM tree_tree_refs WHERE referred_to_tree_id = t.id) = 0
-- SELECT pfrd.path, pf.filename, pf.version_ids FROM pack_files pf, relative_dirs pfrd WHERE (SELECT COUNT(*) FROM packed_blobs WHERE pack_file_id = pf.id) = 0 AND (SELECT COUNT(*) FROM trees WHERE pack_file_id = pf.id) = 0 AND pf.relative_dir_id = pfrd.id AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT rd.path, b.filename, b.version_ids FROM unpacked_blobs b, relative_dirs rd WHERE (b.relative_dir_id = rd.id) AND (SELECT COUNT(*) FROM tree_unpacked_blob_refs WHERE referred_to_unpacked_blob_id = b.id) = 0 AND (SELECT COUNT(*) FROM backup_record_unpacked_blob_refs WHERE referred_to_unpacked_blob_id = b.id) = 0 AND (b.locked_until IS NULL OR b.locked_until < ?)
-- SELECT DISTINCT rd.path, pf.filename FROM backup_record_packed_blob_refs brpbr, packed_blobs pb, pack_files pf, relative_dirs rd WHERE brpbr.referred_to_packed_blob_id = pb.id AND pb.pack_file_id = pf.id AND pf.relative_dir_id = rd.id AND brpbr.backup_record_id = ? AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT DISTINCT rd.path, ub.filename FROM backup_record_unpacked_blob_refs brubr, unpacked_blobs ub, relative_dirs rd WHERE brubr.referred_to_unpacked_blob_id = ub.id AND ub.relative_dir_id = rd.id AND brubr.backup_record_id = ? AND (ub.locked_until IS NULL OR ub.locked_until < ?)
-- SELECT DISTINCT rd.path, pf.filename FROM trees t, pack_files pf, relative_dirs rd WHERE t.id = ? AND t.pack_file_id = pf.id AND pf.relative_dir_id = rd.id AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT DISTINCT rd.path, pf.filename FROM tree_packed_blob_refs tpbr, packed_blobs pb, pack_files pf, relative_dirs rd WHERE tpbr.referring_tree_id = ? AND tpbr.referred_to_packed_blob_id = pb.id AND pb.pack_file_id = pf.id AND pf.relative_dir_id = rd.id AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT DISTINCT rd.path, ub.filename FROM tree_unpacked_blob_refs tubr, unpacked_blobs ub, relative_dirs rd WHERE tubr.referring_tree_id = ? AND tubr.referred_to_unpacked_blob_id = ub.id AND ub.relative_dir_id = rd.id AND (ub.locked_until IS NULL OR ub.locked_until < ?)
-- SELECT COUNT(*) FROM packed_blobs WHERE pack_file_id = ? AND blob_identifier = ? AND offset = ? AND length = ? AND stretch_encryption_key = ? AND compression_type = ? AND valid = 1
-- SELECT id FROM packed_blobs WHERE pack_file_id = ? AND blob_identifier = ? AND offset = ? AND length = ? AND stretch_encryption_key = ? AND compression_type = ?
-- SELECT id FROM unpacked_blobs WHERE relative_dir_id = ? AND filename = ?
-- SELECT rd.path, ub.filename, ub.length, ub.stretch_encryption_key, ub.compression_type, ub.id FROM unpacked_blobs ub, relative_dirs rd WHERE ub.valid = 1 AND ub.relative_dir_id = rd.id AND ub.blob_identifier = ? AND ub.storage_class = ? ORDER BY ub.id DESC
-- SELECT id FROM unpacked_blobs WHERE relative_dir_id within insertValidUnpackedBlobLoc failed: %@
-- SELECT t.id FROM pack_files pf, trees t, relative_dirs rd WHERE pf.id = t.pack_file_id AND t.blob_identifier = ? AND t.offset = ? AND t.length = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ? ORDER BY t.id DESC LIMIT 1
-- SELECT t.id FROM pack_files pf, trees t, relative_dirs rd WHERE pf.id = t.pack_file_id AND t.blob_identifier = ? AND t.offset = ? AND t.length = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ?
-- SELECT pb.id FROM packed_blobs pb, pack_files pf, relative_dirs rd WHERE pb.pack_file_id = pf.id AND pb.blob_identifier = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ? AND pb.offset = ? AND pb.length = ? ORDER BY pb.id DESC LIMIT 1
-- SELECT pb.id FROM packed_blobs pb, pack_files pf, relative_dirs rd WHERE pb.pack_file_id = pf.id AND pb.blob_identifier = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ? AND pb.offset = ? AND pb.length = ? AND pb.valid = 1 ORDER BY pb.id DESC
-- SELECT ub.id FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND ub.filename = ? AND rd.path = ? AND ub.storage_class = ? AND ub.valid = 1 ORDER BY ub.id DESC
-- SELECT ub.id FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND ub.filename = ? AND rd.path = ? AND ub.valid = 1 ORDER BY ub.id DESC
-- SELECT id FROM unpacked_blobs WHERE blob_identifier = ? AND storage_class = ? AND valid = 1 ORDER BY id DESC
-- SELECT pfrd.path, pf.filename, t.offset, t.length, t.blob_identifier, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, trees t WHERE pf.id = t.pack_file_id AND pf.relative_dir_id = pfrd.id AND pf.committed = 0 AND (SELECT COUNT(*) FROM tree_tree_refs WHERE referred_to_tree_id = t.id) = 0
-- SELECT pfrd.path, pf.filename, pb.offset, pb.length, pb.stretch_encryption_key, pb.compression_type, pb.id, pf.committed, pf.locked_until, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, packed_blobs pb WHERE pb.valid = 1 AND pf.id = pb.pack_file_id AND pf.relative_dir_id = pfrd.id AND pb.blob_identifier = ? AND pf.storage_class = ? ORDER BY pb.id DESC LIMIT 1
-- SELECT pfrd.path, pf.filename, t.offset, t.length, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, trees t WHERE pf.id = t.pack_file_id AND pf.relative_dir_id = pfrd.id AND t.blob_identifier = ? AND t.valid = 1 ORDER BY pf.id DESC LIMIT 1
-- SELECT COUNT(*), SUM(length) FROM unpacked_blobs WHERE stretch_encryption_key IS NULL OR compression_type IS NULL
-- SELECT rd.path, ub.filename FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND ub.id IN (SELECT id FROM unpacked_blobs WHERE stretch_encryption_key IS NULL OR compression_type IS NULL) ORDER BY rd.path, ub.filename
-- SELECT rd.path, ub.filename, ub.length, ub.stretch_encryption_key, ub.compression_type, ub.item_checksum, ub.id, ub.locked_until FROM unpacked_blobs ub, relative_dirs rd WHERE ub.valid = 1 AND ub.relative_dir_id = rd.id AND ub.blob_identifier = ? AND ub.storage_class = ? ORDER BY ub.id
-- SELECT ub.id, ub.stretch_encryption_key, ub.compression_type FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND rd.path = ? AND ub.filename = ? AND ub.valid =1 ORDER BY ub.id DESC
-- SELECT id FROM pack_files WHERE relative_dir_id = ? AND filename = ?
-- SELECT rd.path, pf.filename FROM pack_files pf, relative_dirs rd WHERE pf.relative_dir_id = rd.id AND (SELECT COUNT(*) FROM packed_blobs WHERE pack_file_id = pf.id) = 0 AND (SELECT COUNT(*) FROM trees WHERE pack_file_id = pf.id) = 0
-- SELECT SUM(length) FROM pack_files
-- SELECT SUM(length) FROM unpacked_blobs
-- SELECT SUM(length) FROM pack_files WHERE storage_class = ?
-- SELECT SUM(length) FROM unpacked_blobs WHERE storage_class = ?
-- SELECT pfrd.path, pf.filename, t.offset, t.length, t.blob_identifier, pf.is_large_pack FROM pack_files pf, relative_dirs pfrd, trees t WHERE pf.id = t.pack_file_id AND pf.relative_dir_id = pfrd.id AND (SELECT COUNT(*) FROM backup_record_tree_refs WHERE referred_to_tree_id = t.id) = 0 AND (SELECT COUNT(*) FROM tree_tree_refs WHERE referred_to_tree_id = t.id) = 0
-- SELECT pfrd.path, pf.filename, pf.version_ids FROM pack_files pf, relative_dirs pfrd WHERE (SELECT COUNT(*) FROM packed_blobs WHERE pack_file_id = pf.id) = 0 AND (SELECT COUNT(*) FROM trees WHERE pack_file_id = pf.id) = 0 AND pf.relative_dir_id = pfrd.id AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT rd.path, b.filename, b.version_ids FROM unpacked_blobs b, relative_dirs rd WHERE (b.relative_dir_id = rd.id) AND (SELECT COUNT(*) FROM tree_unpacked_blob_refs WHERE referred_to_unpacked_blob_id = b.id) = 0 AND (SELECT COUNT(*) FROM backup_record_unpacked_blob_refs WHERE referred_to_unpacked_blob_id = b.id) = 0 AND (b.locked_until IS NULL OR b.locked_until < ?)
-- SELECT DISTINCT rd.path, pf.filename FROM backup_record_packed_blob_refs brpbr, packed_blobs pb, pack_files pf, relative_dirs rd WHERE brpbr.referred_to_packed_blob_id = pb.id AND pb.pack_file_id = pf.id AND pf.relative_dir_id = rd.id AND brpbr.backup_record_id = ? AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT DISTINCT rd.path, ub.filename FROM backup_record_unpacked_blob_refs brubr, unpacked_blobs ub, relative_dirs rd WHERE brubr.referred_to_unpacked_blob_id = ub.id AND ub.relative_dir_id = rd.id AND brubr.backup_record_id = ? AND (ub.locked_until IS NULL OR ub.locked_until < ?)
-- SELECT DISTINCT rd.path, pf.filename FROM trees t, pack_files pf, relative_dirs rd WHERE t.id = ? AND t.pack_file_id = pf.id AND pf.relative_dir_id = rd.id AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT DISTINCT rd.path, pf.filename FROM tree_packed_blob_refs tpbr, packed_blobs pb, pack_files pf, relative_dirs rd WHERE tpbr.referring_tree_id = ? AND tpbr.referred_to_packed_blob_id = pb.id AND pb.pack_file_id = pf.id AND pf.relative_dir_id = rd.id AND (pf.locked_until IS NULL OR pf.locked_until < ?)
-- SELECT DISTINCT rd.path, ub.filename FROM tree_unpacked_blob_refs tubr, unpacked_blobs ub, relative_dirs rd WHERE tubr.referring_tree_id = ? AND tubr.referred_to_unpacked_blob_id = ub.id AND ub.relative_dir_id = rd.id AND (ub.locked_until IS NULL OR ub.locked_until < ?)
-- SELECT COUNT(*) FROM packed_blobs WHERE pack_file_id = ? AND blob_identifier = ? AND offset = ? AND length = ? AND stretch_encryption_key = ? AND compression_type = ? AND valid = 1
-- SELECT id FROM packed_blobs WHERE pack_file_id = ? AND blob_identifier = ? AND offset = ? AND length = ? AND stretch_encryption_key = ? AND compression_type = ?
-- SELECT id FROM unpacked_blobs WHERE relative_dir_id = ? AND filename = ?
-- SELECT rd.path, ub.filename, ub.length, ub.stretch_encryption_key, ub.compression_type, ub.id FROM unpacked_blobs ub, relative_dirs rd WHERE ub.valid = 1 AND ub.relative_dir_id = rd.id AND ub.blob_identifier = ? AND ub.storage_class = ? ORDER BY ub.id DESC
-- SELECT id FROM unpacked_blobs WHERE relative_dir_id within insertValidUnpackedBlobLoc failed: %@
-- SELECT t.id FROM pack_files pf, trees t, relative_dirs rd WHERE pf.id = t.pack_file_id AND t.blob_identifier = ? AND t.offset = ? AND t.length = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ? ORDER BY t.id DESC LIMIT 1
-- SELECT t.id FROM pack_files pf, trees t, relative_dirs rd WHERE pf.id = t.pack_file_id AND t.blob_identifier = ? AND t.offset = ? AND t.length = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ?
-- SELECT pb.id FROM packed_blobs pb, pack_files pf, relative_dirs rd WHERE pb.pack_file_id = pf.id AND pb.blob_identifier = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ? AND pb.offset = ? AND pb.length = ? ORDER BY pb.id DESC LIMIT 1
-- SELECT pb.id FROM packed_blobs pb, pack_files pf, relative_dirs rd WHERE pb.pack_file_id = pf.id AND pb.blob_identifier = ? AND pf.relative_dir_id = rd.id AND rd.path = ? AND pf.filename = ? AND pb.offset = ? AND pb.length = ? AND pb.valid = 1 ORDER BY pb.id DESC
-- SELECT ub.id FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND ub.filename = ? AND rd.path = ? AND ub.storage_class = ? AND ub.valid = 1 ORDER BY ub.id DESC
-- SELECT ub.id FROM unpacked_blobs ub, relative_dirs rd WHERE ub.relative_dir_id = rd.id AND ub.filename = ? AND rd.path = ? AND ub.valid = 1 ORDER BY ub.id DESC
-- SELECT id FROM unpacked_blobs WHERE blob_identifier = ? AND storage_class = ? AND valid = 1 ORDER BY id DESC
